---
apiVersion: v1
kind: Service
metadata:
  name: embargo-butler-enqueue
  labels:
    app: enqueue
spec:
  type: LoadBalancer
  ports:
  - name: enqueue-webhook
    port: 8080
    protocol: TCP
    targetPort: 8000
  selector:
    app: enqueue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: embargo-butler-enqueue
  labels:
    app: enqueue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enqueue
  template:
    metadata:
      labels:
        app: enqueue
    spec:
      containers:
      - name: enqueue
        image: "ghcr.io/lsst-dm/embargo-butler-enqueue:prod"
        imagePullPolicy: Always
        env:
        - name: PROFILE
          value: prompt-processing-dev
        - name: DATASET_REGEXP
          value: 'LSSTCam/\d{8}/\w*/[\w.]*\.fits$'
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis
              key: redis-password
        - name: NOTIFICATION_SECRET
          value: ""
        resources:
          limits:
            cpu: "1"
