---
apiVersion: v1
kind: Service
metadata:
  name: embargo-butler-presence
  labels:
    app: presence
  annotations:
    metallb.universe.tf/address-pool: sdf-services
spec:
  type: LoadBalancer
  ports:
  - name: presence-http
    port: 8080
    protocol: TCP
    targetPort: 8000
  selector:
    app: presence
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: embargo-butler-presence
  labels:
    app: presence
    site: summit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: presence
      site: summit
  template:
    metadata:
      labels:
        app: presence
        site: summit
    spec:
      containers:
      - name: presence
        image: "ghcr.io/lsst-dm/embargo-butler-presence:prod"
        env:
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis
              key: redis-password
        resources:
          limits:
            cpu: 1
            memory: "500Mi"
          requests:
            cpu: "250m"
            memory: "100Mi"
